apiVersion: v1
kind: Service
metadata:
  name: {{ include "sendgridmock.fullname" . }}
  labels:
    {{- include "sendgridmock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
      protocol: TCP
      name: http
  selector:
    {{- include "sendgridmock.selectorLabels" . | nindent 4 }}
